apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-bank-showcase
  namespace: demodog
  labels:
    app.kubernetes.io/name: insecure-bank-showcase
    demodog.release: insecure-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: insecure-bank-showcase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insecure-bank-showcase
        demodog.release: insecure-bank
      annotations:
        admission.datadoghq.com/java-lib.version: "latest"
    spec:
      containers:
        - name: insecure-bank-showcase
          image: ghcr.io/manuel-alvarez-alvarez/demodog-insecure-bank-showcase:latest
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-bank-tutorial
  namespace: demodog
  labels:
    app.kubernetes.io/name: insecure-bank-tutorial
    demodog.release: insecure-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: insecure-bank-tutorial
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insecure-bank-tutorial
        demodog.release: insecure-bank
        admission.datadoghq.com/enabled: "false"
    spec:
      containers:
        - name: insecure-bank-tutorial
          image: ghcr.io/manuel-alvarez-alvarez/demodog-insecure-bank-tutorial:latest
          ports:
            - containerPort: 80