apiVersion: v1
kind: Service
metadata:
  name: insecure-bank
  namespace: demodog
spec:
  selector:
    app.kubernetes.io/name: insecure-bank
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080