apiVersion: v1
kind: Service
metadata:
  name: insecure-bank-showcase-lb
  labels:
    app.demodog.com/type: showcase
    app.demodog.com/release: insecure-bank
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: insecure-bank-showcase
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: insecure-bank-tutorial-lb
  labels:
    app.demodog.com/type: tutorial
    app.demodog.com/release: insecure-bank
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: insecure-bank-tutorial
  ports:
    - name: http
      port: 80
      targetPort: 80